class ElementType:
    GROUND = "ground"
    PARKING_SPACE = "parking_space"
    ROAD = "driving_lane"
    SIDEWALK = "pedestrian_path"
    RAMP = "slope"
    PILLAR = "pillar"
    WALL = "wall"
    ENTRANCE = "entrance"
    EXIT = "exit"
    STAIRCASE = "staircase"
    ELEVATOR = "elevator"
    CHARGING_STATION = "charging_station"
    GUIDANCE_SIGN = "guidance_sign"
    SAFE_EXIT = "safe_exit"
    SPEED_BUMP = "deceleration_zone"
    FIRE_EXTINGUISHER = "fire_extinguisher"
    LANE_LINE = "ground_line"
    CONVEX_MIRROR = "convex_mirror"

    SLAB = "floor_slab"
    WALL_EXTERNAL = "exterior_wall"
    WALL_INTERNAL = "partition_wall"
    SHEAR_WALL = "shear_wall"
    ROOF_PARAPET = "parapet"

    ELEVATOR_SHAFT = "elevator_shaft"
    SERVICE_SHAFT = "pipe_shaft"
    ELEVATOR_HALL = "elevator_lobby"

    CORRIDOR = "corridor"
    LOBBY = "lobby"
    AISLE = "aisle"

    DOOR = "door"
    FIRE_DOOR = "fire_door"
    WINDOW = "window"

    BALCONY = "balcony"
    TERRACE = "terrace"
    AIR_CON_LEDGE = "ac_ledge"
    WINDOW_SILL = "window_sill"

    KITCHEN_ZONE = "kitchen"
    BATHROOM_ZONE = "bathroom"
    LIVING_ZONE = "living_room"
    BEDROOM_ZONE = "bedroom"
    STORAGE_ZONE = "storage"

    FIRE_HYDRANT = "fire_hydrant"
    SAFE_EXIT_SIGN = "exit_sign"
    HVAC_VENT = "hvac_vent"
    ELECTRICAL_BOX = "dist_box"

